---
- hosts: all
  sudo: yes

  tasks:

    - name: Run 'apt-get update'
      apt: update_cache=yes


    # start - https://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation

    - name: cmd
      shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

    - name: cmd
      shell: sh -c "echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list"

    - name: Run 'apt-get update'
      apt: update_cache=yes

    - name: Install needed packages
      apt: pkg={{ item }} state=latest
      with_items:
        - lxc-docker

    # end - https://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation
